services:
  dbt:
    container_name: dbt_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dbt/my_project:/usr/app
      - ./wait-for.sh:/opt/wait-for.sh
      - ./dbt/.dbt/profiles.yml:/root/.dbt/profiles.yml:ro
    working_dir: /usr/app
    environment:
      DBT_PROFILES_DIR: "/root/.dbt"
    entrypoint: /bin/bash
    command: >
      -c "/opt/wait-for.sh db:5432 --timeout=60 -- echo 'Postgres is up' &&
          /opt/wait-for.sh af:8080 --timeout=60 -- echo 'Airflow is up' &&
          dbt run &&
          tail -f /dev/null"
    networks:
      - my-network